- name: Install bat in Ubuntu
  become: true
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v{{ bat_version }}/bat-musl_{{ bat_version }}_amd64.deb
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Pop!_OS"