- name: Download go tar file
  ansible.builtin.command:
    cmd: wget https://go.dev/dl/go{{version}}.linux-amd64.tar.gz
 
- name: Delete previous installation
  ansible.builtin.command:
    cmd: rm -rf /usr/local/go
  become: true
 
- name: Extract and move new go folder to /usr/local
  ansible.builtin.command:
    cmd: tar -C /usr/local -xzf go{{version}}.linux-amd64.tar.gz
  become: true
 
- name: Delete downloaded tar file
  ansible.builtin.command:
    cmd: rm -rf go{{version}}.linux-amd64.tar.gz*
 
- name: Add go binary path to ~/.profile
  lineinfile:
    path: ~/.profile
    line: 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'
    create: true
    state: present
 
- name: Source updated profile and test go version
  ansible.builtin.command:
    cmd: . ~/.profile && go version