---
- name: Install flatpak in Ubuntu
  become: true
  apt:
    name:
      - flatpak
    state: present
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Pop!_OS"

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user