---
- name: Install nvim in Linux
  import_tasks: linux.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Pop!_OS" or ansible_distribution == "Fedora"

- name: Generate :help pages
  shell: nvim --headless -c 'helptags ALL' -c quit